### ISSUE TITLE
terraform replaces vault token each terraform apply

### ISSUE THREAD

**Issue by AidiSaifeddine** [makezbs/terraform-vault-token#1]
Hello,

I am using terrafrom to create vault tokens and store them in AWS Parameter store but each time I run **terraform apply** the tokens are changed even though I don't change anything in the configuration file.  Do you have any idea why is that ?

This is my module:

****resource "vault_token" "token" {

  display_name = var.token_name
  policies     = var.token_policies
  no_parent    = true
  ttl          = "24h"
  renewable    = true
  renew_min_lease = 43200
  renew_increment = 86400

}

resource "aws_ssm_parameter" "secret" {
  name        = "/vault/${var.token_name}"
  description = vault_token.token.lease_duration
  type        = "SecureString"
  value       = vault_token.token.client_token
}****

and here I call it:

**module "create-token" {
  providers = {
    aws = aws.ireland
  }
  source = "./modules/create-token"
  for_each = var.tokens
  token_name = each.value.name
  token_policies = each.value.policies
  depends_on = [ module.create-policy ]
}**

**Comment by ingvarch** [comment]
Is it still actual ? Sorry for delay.

I guess it is question not to me :)
